import { Service, ServiceCategory, Provider } from '../types';

export const serviceCategories: ServiceCategory[] = [
  {
    id: '1',
    name: 'Auto Care',
    description: 'Professional car care services',
    servicesCount: 6,
    icon: 'car',
  },
  {
    id: '2',
    name: 'Home Cleaning',
    description: 'Keep your home spotless',
    servicesCount: 5,
    icon: 'home',
  },
  {
    id: '3',
    name: 'Plumbing & Electrical',
    description: 'Expert home maintenance',
    servicesCount: 5,
    icon: 'wrench',
  },
  {
    id: '4',
    name: 'Handyman & Repairs',
    description: 'Fix it all',
    servicesCount: 5,
    icon: 'build',
  },
  {
    id: '5',
    name: 'Beauty & Wellness',
    description: 'Beauty services at home',
    servicesCount: 5,
    icon: 'cut',
  },
  {
    id: '6',
    name: 'Gardening & Outdoor',
    description: 'Transform your outdoor space',
    servicesCount: 5,
    icon: 'leaf',
  },
  {
    id: '7',
    name: 'Appliances & IT',
    description: 'Tech and appliance experts',
    servicesCount: 5,
    icon: 'settings',
  },
];

export const featuredServices: Service[] = [
  {
    id: '1',
    title: 'Premium Car Detailing',
    description: 'Full interior and exterior detailing with ceramic coating option',
    price: '$150 - $300',
    location: 'Los Angeles, CA',
    rating: 4.9,
    reviews: 127,
    image: 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=800',
    category: 'Auto Care',
  },
  {
    id: '2',
    title: 'Deep Home Cleaning',
    description: 'Comprehensive deep cleaning service for your entire home',
    price: '$100 - $250',
    location: 'San Francisco, CA',
    rating: 4.8,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    category: 'Home Cleaning',
  },
  {
    id: '3',
    title: 'Emergency Plumbing',
    description: '24/7 emergency plumbing services for all your needs',
    price: '$80 - $200',
    location: 'New York, NY',
    rating: 4.7,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800',
    category: 'Plumbing',
  },
  {
    id: '4',
    title: 'Professional Painting',
    description: 'Interior and exterior painting with premium materials',
    price: '$200 - $500',
    location: 'Austin, TX',
    rating: 4.9,
    reviews: 73,
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800',
    category: 'Handyman',
  },
  {
    id: '5',
    title: 'Salon at Home',
    description: 'Full salon experience in the comfort of your home',
    price: '$50 - $150',
    location: 'Miami, FL',
    rating: 5.0,
    reviews: 94,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800',
    category: 'Beauty',
  },
  {
    id: '6',
    title: 'Landscape Design',
    description: 'Transform your outdoor space with professional landscaping',
    price: '$300 - $1000',
    location: 'Seattle, WA',
    rating: 4.8,
    reviews: 62,
    image: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800',
    category: 'Gardening',
  },
  {
    id: '7',
    title: 'Computer Repair & Setup',
    description: 'Expert computer repair and network setup services',
    price: '$60 - $150',
    location: 'Boston, MA',
    rating: 4.9,
    reviews: 118,
    image: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=800',
    category: 'IT',
  },
  {
    id: '8',
    title: 'Mobile Car Wash',
    description: 'Professional car wash at your location',
    price: '$40 - $80',
    location: 'Los Angeles, CA',
    rating: 4.6,
    reviews: 201,
    image: 'https://images.unsplash.com/photo-1610647752706-3bb12232b3ab?w=800',
    category: 'Auto Care',
  },
];

export const topProviders: Provider[] = [
  {
    id: '1',
    name: 'John Smith',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    category: 'Auto Care',
    rating: 4.9,
    jobsCompleted: 250,
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    category: 'Home Cleaning',
    rating: 5.0,
    jobsCompleted: 180,
  },
  {
    id: '3',
    name: 'Mike Chen',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    category: 'Plumbing',
    rating: 4.8,
    jobsCompleted: 320,
  },
  {
    id: '4',
    name: 'Emily Davis',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    category: 'Beauty & Wellness',
    rating: 4.9,
    jobsCompleted: 210,
  },
];